### ISSUE TITLE
Should add support for Sixel graphics.

### ISSUE THREAD

**Issue by migueldeicaza** [migueldeicaza/SwiftTerm#29]

**Comment by palmin** [comment]
I have started working on this as it seems like a nice way to get familiar with the library.

**Comment by palmin** [comment]
I have a DcsHandler registered that can decode Sixel sequences making producing TTImage (UIImage or NSImage depending on platform).

I imagine this is eventually embedded in NSAttributtedString through NSTextAttachment but I wonder what the nicest way is to pass this along to Terminal.

Let me know if you have preferences on how the data should flow @migueldeicaza. 

Otherwise I will try stuff and eventually come up with something. 😄 

<img width="222" alt="image" src="https://user-images.githubusercontent.com/1230554/80493841-352c8100-8966-11ea-8e0e-d16219d79f35.png">

**Comment by migueldeicaza** [comment]
WOW - this is fabulous!

This is a great question, and one I had not given much thought to.   

Adding a pointer to each cell sounds like it would be very wasteful (64 bits).

What I think we could do is introduce another `TinyAtom` field in `CharData` which takes 2 bytes and is used to encode a peer payload.  We would need to change `TinyAtom` to be generic, so that instead of being a mapping of Int16 to String, it would be an Int16 to TTImage.    

The current use of `TinyAtom` is for `urlPayload` which shares the same URL among many different cells, so it makes sense there (despite the fact that this puts an upper limit on the number of links that can be rendered at 64k).   

For this scenario, we would need to release images no longer in use, so I think we would need a `deinit` to make sure that we drop the reference to the image.

**Comment by palmin** [comment]
Thanks you. Your explanation makes a lot of sense and I can feel my understanding of SwiftTerm growing.

Looking at CharData it seems to be a [point](https://github.com/migueldeicaza/SwiftTerm/blob/ad17586e6ac5aae449530333efb7b9ab73c90e64/SwiftTerm/Sources/SwiftTerm/CharData.swift#L234-L243) that it doesn't grow beyond 16 bytes. I made changes such that payload for the existing 16-bit TinyAtom can point to either strings or images. With the help of Swift enums this can be done nicely.

But I have a problem dropping the reference to the image. The natural place to do this cleanup is in deinit for CharData but this is a struct that doesn't support deinit and in any case the same TinyAtom code could be used by live CharData. 

I could step out one level and try to cleanup in BufferLine deinit and when entries are overwritten, but this still risks cleaning up images referenced by TinyAtom used in other CharData just because one is being overwritten.

I will try to think of ways to solve this. Right now everything I come up feels like manually trying to do reference counted memory management.

Suggestions are extremely welcome.

**Comment by migueldeicaza** [comment]
Hello!

Ouch - this means we will have to manually check for a valid TinyAtom every time we get rid of a CharData - I don’t like this, easy to miss and leak.

Storing a pointer would bloat the cells.

One possible idea, I am not exactly a fan, but could also help the theoretical limit on urlPayload:

We could implement a garbage collector, which would scan all CharData and only keep atoms alive that are referenced and clear the others.   

To make this robust, the TinyAtom for images would need to be part of the buffer and we could scan the contents either on a timer or with some heuristic (N printed characters, N printed sixels, N scrolling)

**Comment by palmin** [comment]
Thanks. I will try garbage collection. 

Perhaps it isn't as bad in practice as it sounds. 🙂

**Comment by migueldeicaza** [comment]
I am still trying to digest how Xterm does it, here is the code:

https://github.com/Maximus5/xterm/blob/master/src/graphics_sixel.c

It looks like they keep a parallel array with graphics, with the location where it was allocated.   The problem is that this could get out of sync with delete/insert operations.   Need to study how they deal with it

**Comment by migueldeicaza** [comment]
I just realized that we are not limited to TinyAtoms, because you either have a character or an image.   The TinyAtoms were needed because they were additional data for a character.

So what we should do is reuse the `CharData.code` when we have a flag indicating that this is a sixel value (we can use the `unused` field to store the flag.   So that would eliminate the limit on 64k images.

**Comment by palmin** [comment]
I have submitted a pull request that only does decoding of sixel images #110 after some failed attempts to get the image rendering and data flow to work well.

**Comment by migueldeicaza** [comment]
Thank you so much for this, this is a great starting point, we can merge that part, and then sort out the rest, I am still thinking about how to deal with the garbage without bloating the structure.

**Comment by migueldeicaza** [comment]
Completed the sixel work.
